### ISSUE TITLE
Falemos removing Chat functionality from Foundry?

### ISSUE THREAD

**Issue by BabyfaceFinlayson** [jvir/foundry-falemos#33] opened 2021-06-07 19:16 UTC
When I added a tile in Foundry, the Chat and Macro bars permanently disappeared. Deleting the modules I had installed, one by one, Falemos was the module causing the problem.

![Screenshot_2021-06-05_at_07 46 53](https://user-images.githubusercontent.com/81977646/121075493-281acc00-c7cd-11eb-9566-d29edd298e8e.png)

**Comment by BabyfaceFinlayson** [comment] 2021-06-07 19:17
Obviously this is a significant issue.

**Comment by jvir** [comment] 2021-06-07 20:37
Can you check that in the global configuration of falemos in the scene you don't have "Hide sidebar" and "Hide hotbar" checked?

**Comment by jvir** [comment] 2021-06-07 20:39
If not marked, can you tell me the steps to reproduce the problem? That would help me because I am not able to reproduce it by myself.

**Comment by BabyfaceFinlayson** [comment] 2021-06-08 23:33
![Screenshot 2021-06-09 at 00 20 56](https://user-images.githubusercontent.com/81977646/121270806-4ad6de80-c8ba-11eb-8e0e-e95700570119.png)

**Comment by BabyfaceFinlayson** [comment] 2021-06-08 23:35
When the problem arose, I deleted all modules and added them back one by one in alphabetical order. These are the modules I got to before installing Falemos and experiencing the same issue again:
ae-to-chat--v0.2.11;
actually-private-rolls--v0.2;
ambientdoors--v2.2.3;
arms-reach--v1.1.1;
autocomplete-inline-properties--v1.2.0;
autocomplete-whisper--v0.3.3;
autorotate--vv1.1.2;
BetterAmbientLoop--v1.1.2.1;
chat-portrait--v0.2.1;
clocks--v1.3.5;
_CodeMirror--v5.58.3-fvtt3;
foundry-combat-focus--v1.4.0;
CommunityLighting--v0.3.3;
compendium-folders--v2.2.44;
cone-measurement-angle--v0.1.10;
cursor-hider--v1.1.7;
designerdoors--v1.0.1;
df-scene-enhance--v3.3.3;
dice-so-nice--v3.3.4;
dice-calculator--v0.6.8;
difficultterrain--v1.0.10;
DragTransfer--v1.1.0;
drag-ruler--v1.7.0;
dragupload--v1.5.3;
dynamic-illumination--v0.9.0;
easy-exports--v0.6.1;
EasyTable--v1.3.2;
easy-target--v2.11;
enhanced-terrain-layer--v1.0.25;

**Comment by BabyfaceFinlayson** [comment] 2021-06-08 23:36
I can only imagine that it was a conflict. I can't test at the moment. I'll get back to you when I have.

**Comment by jvir** [comment] 2021-06-09 06:35
Could you try a new world without modules and with the same system?

**Comment by jvir** [comment] 2021-09-06 08:25
I am closing this report because I am unable to reproduce it and there have been no further comments to the requests for information.

**Closed as completed by jvir** 2021-09-06 08:25 UTC
Labels: question
